[profile.default]
src = "src"
out = "out"
libs = ["lib"]
extra_output = ["abi"]

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@zk-kit/lean-imt.sol=lib/zk-kit.solidity/packages/lean-imt/contracts/",
    "@semaphore/contracts/=lib/semaphore/packages/contracts/",
    "poseidon-solidity/=lib/poseidon-solidity/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
# a link to the setup for semaphore-protocol can be found under https://github.com/csiejimmyliu/semaphore/tree/new_branch/packages/cli-template-contracts-foundry
